### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Fylipp** [christophebedard/JavaWord#1]
^^

**Comment by ararslan** [comment]
So that there's finally a better IDE on Windows than Notepad, of course.

**Comment by christophebedard** [comment]
¯\\\_(ツ)\_/¯

**Comment by JIceberg** [comment]
No no you were asking the right question here.

**Comment by litehed** [comment]
^^

**Comment by faaizajaz** [comment]
This makes me feel sick. Good job.

**Comment by budgetdevv** [comment]
We need JavaConsole
